### ISSUE TITLE
Automatically update Risk CSV

### ISSUE THREAD

**Issue by amhanson9** [uga-libraries/accessioning-scripts#10]
**Location:** format_analysis.py, when read existing full_risk_data.csv into df_results 

**Description:** When the full_risk_data.csv exists from a previous iteration of running the script, update to it to remove deleted files and add new files, including calculating their risk information, like the update_fits() function. Right now, the archivist must delete the full_risk_data.csv for the data to be updated, which means losing any edits the archivist has already made.

**Comment by amhanson9** [comment]
@emkaser Is there a clear use case for needing to add new files to the risk csv? Removing deleting things is much simpler than adding new things, but it can still be done if there is a need. Have you added new files to an accession after you started running these reports?

**Comment by emkaser** [comment]
@amhanson9 This is a very uncommon situation so I don't think we need to add this functionality at this time. I think this would only happen if there is a long pause mid-accession, e.g. waiting for a particular piece of equipment to get data off of transfer media.

**Comment by amhanson9** [comment]
The script will print a list of files that are only in the accession folder and not risk as an alert if that ever happens.
